config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :articles, only: [:index]

  resources :feeds, only: [:new, :create, :show] do
    resources :articles do
      member do
        get :bookmark
      end
    end

    member do
      get :refresh
      delete :unsubscribe
    end
  end

  resources :bookmarked_articles, only: [:index, :create, :destroy]


  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#failure", via: [:get, :post]
  match "/logout", to: "sessions#destroy", as: :logout, via: :delete
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :feed, inverse_of: :articles

  has_many :user_bookmarks, class_name: "BookmarkedArticle"
  has_many :users, through: :user_bookmarks

  validates :external_id, presence: true
  validates :feed_id, presence: true
  validates :title, presence: true
  validates :url, presence: true

  scope :bookmarked_by_user, ->(user) { where(id: user.bookmarked_articles.pluck(:article_id)) }
  scope :for_feed, ->(feed) { where(feed_id: (feed.is_a?(Feed) ? feed.id : feed)) }

  default_scope -> { order("published_at DESC") }

  def bookmark_for_user(user)
    user.bookmarked_articles.create(article: self)
  end

  def bookmarked_by_user?(user)
    user.bookmarked_articles.where(article: self).any?
  end
end

app/models/bookmarked_article.rb
class BookmarkedArticle < ActiveRecord::Base
  belongs_to :article, inverse_of: :user_bookmarks
  belongs_to :user, inverse_of: :bookmarked_articles

  scope :for_user, ->(user) { where(user: user) }
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :feed_subscriptions, dependent: :destroy
  has_many :users, through: :feed_subscriptions

  has_many :articles, inverse_of: :feed, dependent: :destroy

  validates :url, presence: true

  before_create :fetch_feed_and_load_title
  after_create :refresh!

  scope :bookmarked_by_user, ->(user) do
    def self.bookmarked_articles(user)
      BookmarkedArticle.preload(:article).for_user(user)
    end

    where(id: bookmarked_articles(user).map { |bookmark| bookmark.article.feed_id })
  end

  def name
    cached_title || url.truncate(50)
  end

  def refresh!
    RefreshFeedJob.perform_now(self)
  end

  def refresh_later!
    RefreshFeedJob.perform_later(self)
  end

  def unsubscribe_user(user)
    subscription = feed_subscriptions.where(user: user).first
    return unless subscription

    subscription.destroy
  end

  protected

  def fetch_feed_and_load_title
    feed = Feedjira::Feed.fetch_and_parse(url)
    self.cached_title = feed.title
  rescue
    nil
  end
end

app/models/feed_subscription.rb
class FeedSubscription < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user

  validates_uniqueness_of :user_id, message: "already subscribed to this feed", scope: [:feed_id]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feed_subscriptions, inverse_of: :user
  has_many :feeds, through: :feed_subscriptions
  has_many :articles, through: :feeds
  has_many :bookmarked_articles, inverse_of: :user

  validates :name, presence: true
  validates :uid, presence: true
  validates :provider, presence: true

  def self.from_omniauth(auth)
    find_or_initialize_by(provider: auth["provider"], uid: auth["uid"]).tap do |user|
      user.name = auth["info"]["name"]
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end
  helper_method :current_user

  def user_signed_in?
    !!current_user
  end
  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to root_path unless user_signed_in?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = current_user.articles
  end

  def bookmark
    @article = Article.find(params[:id])

    respond_to do |format|
      if (@bookmarked_article = @article.bookmark_for_user(current_user))
        format.js { render partial: "articles/article", locals: { article: @article } }
        format.html { redirect_to :back }
      else
        format.js { render text: "Unable to bookmark article" }
        format.html { redirect_to :back, alert: "Unable to bookmark article" }
      end
    end
  end
end

app/controllers/bookmarked_articles_controller.rb
class BookmarkedArticlesController < ApplicationController
  def index
    if params[:feed_id].present?
      @bookmarked_articles = Article.bookmarked_by_user(current_user).for_feed(params[:feed_id])
    else
      @bookmarked_articles = Article.bookmarked_by_user(current_user)
    end

    @bookmarked_feeds = Feed.bookmarked_by_user(current_user)
  end

  def destroy
    @bookmarked_article = current_user.bookmarked_articles.find(params[:id])

    respond_to do |format|
      if @bookmarked_article.destroy
        format.js { render partial: "articles/article", locals: { article: @bookmarked_article.article } }
        format.html { redirect_to :back }
      else
        format.js { render text: "Unable to remove bookmark" }
        format.html { redirect_to :back, alert: "Unable to remove bookmark"}
      end
    end
  end

  protected

  def bookmarked_article_params
    params.require(:bookmarked_article).permit(:article_id)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :find_feed, only: [:show, :refresh, :unsubscribe]

  def new
    @feed = Feed.new
    @feed.users.push(current_user)
  end

  def create
    @feed = Feed.find_or_initialize_by(url: params[:feed][:url])
    @feed.users.push(current_user)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to root_path, notice: "Feed created" }
        format.js { @feed }
      else
        format.html { render "new" }
        format.js { @feed.errors }
      end
    end
  end

  def show
  end

  def refresh
    @feed.refresh!

    redirect_to @feed
  end

  def unsubscribe
    @feed.unsubscribe_user(current_user)
    redirect_to root_path, notice: "Unsubscribed from #{@feed.name}"
  end

  protected

  def feed_params
    params.require(:feed).permit(:url)
  end

  def find_feed
    @feed = current_user.feeds.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if current_user
      redirect_to articles_path
    else
      render "application/_signed_out_index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def create
    user = find_or_create_from_omniauth
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    redirect_to root_path, alert: "Authentication failure"
  end

  protected

  def omniauth_auth
    request.env["omniauth.auth"]
  end

  def find_or_create_from_omniauth
    User.from_omniauth(omniauth_auth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bookmark_article_link(article)
    bookmark = article.user_bookmarks.for_user(current_user).first

    if article.bookmarked_by_user?(current_user)
      link_to bookmark, method: :delete, class: "bookmark-toggle-link tooltipped", data: { tooltip: "Remove Bookmark" } do
        content_tag(:i, "star", class: "material-icons")
      end
    else
      link_to bookmark_feed_article_path(article.feed, article), class: "bookmark-toggle-link tooltipped", data: { tooltip: "Add Bookmark" } do
        content_tag(:i, "star_outline", class: "material-icons")
      end
    end
  end

  def feed_link(name, path, options = {})
    active_class = "active"

    if request.fullpath == path
      if options.has_key?(:class)
        options[:class] << " "
        options[:class] << active_class
      else
        options[:class] = active_class
      end
    end

    link_to(name, path, options)
  end
end

app/views/application/_signed_out_index.html.haml
.container
  .row.login-container
    .center-align
      %h2 Goggle Reader

      = link_to "/auth/google", class: "btn waves-effect waves-light" do
        %i.material-icons.left perm_identity
        Sign in with Google

app/views/articles/_article.html.haml
.card.hoverable
  .card-content
    %span.card-title
      = article.title

    %p= article.summary.html_safe

  .card-action
    = link_to "Read More", article.url, target: "_blank"

    %span.right
      = bookmark_article_link(article)

      = "#{time_ago_in_words(article.published_at)} ago"

app/views/articles/index.html.haml
- content_for(:side_panel) do
  = render 'feeds/list'

- if @articles.present?
  .cards-container
    = render partial: 'article', collection: @articles

- else
  .card-panel
    %h4 No News is Bad News
    %p Subscribe to some news feeds to see articles here

app/views/bookmarked_articles/_list.html.haml
- if @bookmarked_feeds.any?
  .section
    .collection
      = feed_link "All Bookmarked Articles", bookmarked_articles_path, class: "collection-item"

      - @bookmarked_feeds.each do |feed|
        = feed_link feed.name, bookmarked_articles_path(feed_id: feed.id), class: "collection-item", active_condition: params[:feed_id].to_s == feed.id

app/views/bookmarked_articles/index.html.haml
- content_for(:side_panel) do
  = render 'list'

%h4 Bookmarked Articles

- if @bookmarked_articles.any?
  = render partial: 'articles/article', collection: @bookmarked_articles, as: :article

- else
  .well
    You have not bookmarked any articles

app/views/feeds/_form.html.haml
= simple_form_for Feed.new do |f|
  = f.input :url
  = f.submit class: "btn waves-effect waves-light"

app/views/feeds/_list.html.haml
.row
  .section
    .row.center-align
      = link_to "Add Feed", "#add-feed-modal", class: "btn waves-effect waves-light col l12 modal-trigger"

  - if current_user.feeds.any?
    .section
      .collection
        = feed_link "All Feeds", articles_path, class: "collection-item"

        - current_user.feeds.each do |feed|
          = feed_link feed.name, feed_path(feed), class: "collection-item"

  - else
    .card-panel
      %span
        Subscribe to feeds to see them here

app/views/feeds/_modal.html.haml
#add-feed-modal.modal.bottom-sheet
  .modal-content
    %h4 Subscribe To Feed

    = render "feeds/form"

app/views/feeds/index.html.haml
- content_for(:side_panel) do
  = render 'list'

.cards-container
  = render partial: 'article', collection: @articles

app/views/feeds/new.html.haml
.container
  .row
    = render 'form'

app/views/feeds/show.html.haml
- content_for(:side_panel) do
  = render 'list'

%h4= @feed.name

%span.right
  = link_to refresh_feed_path, class: "btn waves-effect waves-light tooltipped", data: { tooltip: "Refresh" } do
    %i.material-icons refresh
  = link_to unsubscribe_feed_path(@feed), method: :delete, class: "btn waves-effect waves-light tooltipped", data: { tooltip: "Unsubscribe" } do
    %i.material-icons delete

.clearfix

.cards-container
  = render partial: 'articles/article', collection: @feed.articles

app/views/layouts/_messages.html.haml
- if flash.any?
  - flash.each do |key, message|
    :coffeescript
      `Materialize.toast("#{message}", 5000, "toast-#{key}")`

app/views/layouts/_navigation.html.haml
.navbar-fixed
  %nav
    .nav-wrapper
      = link_to "Goggle Reader", root_path, class: "brand-logo"

      %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
        %i.material-icons menu

      %ul.right.hide-on-med-and-down
        = render "layouts/navigation_links"

      %ul.side-nav#mobile-demo
        = render "layouts/navigation_links"

app/views/layouts/_navigation_links.html.haml
%li
  = link_to "Bookmarked Articles", bookmarked_articles_path

%li
  = link_to "Log Out", logout_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/

    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}

    %title
      - if content_for?(:title)
        = yield(:title)
      - else
        Goggle Reader

    = stylesheet_link_tag    "application", media: "all"

    = javascript_include_tag "application"

    = csrf_meta_tags

    %meta{:content => "width=device-width", :name => "viewport"}/

  %body
    - if user_signed_in?
      = render "layouts/messages"

      = render "layouts/navigation"

      .container-fluid
        .row
          .col.s12.m4.l3
            .side-nav-wrapper
              - if content_for?(:side_panel)
                = yield(:side_panel)

          .col.s12.m8.l9
            .section
              = yield

    - else
      = render "signed_out_index"

    = render "feeds/modal"